In [1]:
import pandas as pd

Importing train dataset:

In [36]:
X = pd.read_csv('data/train.csv', delimiter=',')

In [37]:
X.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [38]:
import matplotlib.pyplot as plt

In [43]:
Y = X['Survived']
X.drop(columns=['PassengerId', 'Survived', 'Name', 'Ticket'])

     Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked
0         3    male  22.0      1      0   7.2500   NaN        S
1         1  female  38.0      1      0  71.2833   C85        C
2         3  female  26.0      0      0   7.9250   NaN        S
3         1  female  35.0      1      0  53.1000  C123        S
4         3    male  35.0      0      0   8.0500   NaN        S
..      ...     ...   ...    ...    ...      ...   ...      ...
886       2    male  27.0      0      0  13.0000   NaN        S
887       1  female  19.0      0      0  30.0000   B42        S
888       3  female   NaN      1      2  23.4500   NaN        S
889       1    male  26.0      0      0  30.0000  C148        C
890       3    male  32.0      0      0   7.7500   NaN        Q

[891 rows x 8 columns]

Exploratory data analysis:

In [11]:
Y.head()

0    0
1    1
2    1
3    1
4    0
Name: Survived, dtype: int64

In [ ]:
X.drop(columns=['Name'])

In [ ]:
Lets first see if

Doing a deep study about cabin and the relation with survived:

In [45]:
for idx, row in X.iterrows():
    if len(str(row['Cabin']).split(' ')) > 1:
        print("simblings: {} -> cabin: {}".format(row['SibSp'], row['Cabin']))

simblings: 3 -> cabin: C23 C25 C27
simblings: 0 -> cabin: F G73
simblings: 3 -> cabin: C23 C25 C27
simblings: 0 -> cabin: D10 D12
simblings: 0 -> cabin: B58 B60
simblings: 1 -> cabin: F E69
simblings: 1 -> cabin: C22 C26
simblings: 0 -> cabin: B58 B60
simblings: 1 -> cabin: C22 C26
simblings: 2 -> cabin: B57 B59 B63 B66
simblings: 3 -> cabin: C23 C25 C27
simblings: 1 -> cabin: B96 B98
simblings: 1 -> cabin: B96 B98
simblings: 1 -> cabin: C23 C25 C27
simblings: 1 -> cabin: C22 C26
simblings: 0 -> cabin: B51 B53 B55
simblings: 0 -> cabin: F G63
simblings: 1 -> cabin: C62 C64
simblings: 0 -> cabin: F G73
simblings: 2 -> cabin: B57 B59 B63 B66
simblings: 1 -> cabin: B96 B98
simblings: 0 -> cabin: B82 B84
simblings: 1 -> cabin: B96 B98
simblings: 0 -> cabin: B51 B53 B55

False

In [25]:
X.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [29]:
for idx, row in X.iterrows():
    print(str(row['Cabin']).split(' '))

['nan']
['C85']
['nan']
['C123']
['nan']
['nan']
['E46']
['nan']
['nan']
['nan']
['G6']
['C103']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['D56']
['nan']
['A6']
['nan']
['nan']
['nan']
['C23', 'C25', 'C27']
['nan']
['nan']
['nan']
['B78']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['D33']
['nan']
['B30']
['C52']
['nan']
['nan']
['nan']
['nan']
['nan']
['B28']
['C83']
['nan']
['nan']
['nan']
['F33']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['F', 'G73']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C23', 'C25', 'C27']
['nan']
['nan']
['nan']
['E31']
['nan']
['nan']
['nan']
['A5']
['D10', 'D12']
['nan']
['nan']
['nan']
['nan']
['D26']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C110']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B58', 'B60']
['nan']
['nan']
['nan']
['nan']
['E101']
['D26']
['nan']
['nan']
['nan']
['F', 'E69']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['D47']
['C123']
['nan']
['B86']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['F2']
['nan']
['nan']
['C2']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['E33']
['nan']
['nan']
['nan']
['B19']
['nan']
['nan']
['nan']
['A7']
['nan']
['nan']
['C49']
['nan']
['nan']
['nan']
['nan']
['nan']
['F4']
['nan']
['A32']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['F2']
['B4']
['B80']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['G6']
['nan']
['nan']
['nan']
['A31']
['nan']
['nan']
['nan']
['nan']
['nan']
['D36']
['nan']
['nan']
['D15']
['nan']
['nan']
['nan']
['nan']
['nan']
['C93']
['nan']
['nan']
['nan']
['nan']
['nan']
['C83']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C78']
['nan']
['nan']
['D35']
['nan']
['nan']
['G6']
['C87']
['nan']
['nan']
['nan']
['nan']
['B77']
['nan']
['nan']
['nan']
['nan']
['E67']
['B94']
['nan']
['nan']
['nan']
['nan']
['C125']
['C99']
['nan']
['nan']
['nan']
['C118']
['nan']
['D7']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['A19']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B49']
['D']
['nan']
['nan']
['nan']
['nan']
['C22', 'C26']
['C106']
['B58', 'B60']
['nan']
['nan']
['nan']
['E101']
['nan']
['C22', 'C26']
['nan']
['C65']
['nan']
['E36']
['C54']
['B57', 'B59', 'B63', 'B66']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C7']
['E34']
['nan']
['nan']
['nan']
['nan']
['nan']
['C32']
['nan']
['D']
['nan']
['B18']
['nan']
['C124']
['C91']
['nan']
['nan']
['nan']
['C2']
['E40']
['nan']
['T']
['F2']
['C23', 'C25', 'C27']
['nan']
['nan']
['nan']
['F33']
['nan']
['nan']
['nan']
['nan']
['nan']
['C128']
['nan']
['nan']
['nan']
['nan']
['E33']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['D37']
['nan']
['nan']
['B35']
['E50']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C82']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B96', 'B98']
['nan']
['nan']
['D36']
['G6']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C78']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['E10']
['C52']
['nan']
['nan']
['nan']
['E44']
['B96', 'B98']
['nan']
['nan']
['C23', 'C25', 'C27']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['A34']
['nan']
['nan']
['nan']
['C104']
['nan']
['nan']
['C111']
['C92']
['nan']
['nan']
['E38']
['D21']
['nan']
['nan']
['E12']
['nan']
['E63']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['D']
['nan']
['A14']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B49']
['nan']
['C93']
['B37']
['nan']
['nan']
['nan']
['nan']
['C30']
['nan']
['nan']
['nan']
['D20']
['nan']
['C22', 'C26']
['nan']
['nan']
['nan']
['nan']
['nan']
['B79']
['C65']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['E25']
['nan']
['nan']
['D46']
['F33']
['nan']
['nan']
['nan']
['B73']
['nan']
['nan']
['B18']
['nan']
['nan']
['nan']
['C95']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B38']
['nan']
['nan']
['B39']
['B22']
['nan']
['nan']
['nan']
['C86']
['nan']
['nan']
['nan']
['nan']
['nan']
['C70']
['nan']
['nan']
['nan']
['nan']
['nan']
['A16']
['nan']
['E67']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C101']
['E25']
['nan']
['nan']
['nan']
['nan']
['E44']
['nan']
['nan']
['nan']
['C68']
['nan']
['A10']
['nan']
['E68']
['nan']
['B41']
['nan']
['nan']
['nan']
['D20']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['A20']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C125']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['F4']
['nan']
['nan']
['D19']
['nan']
['nan']
['nan']
['D50']
['nan']
['D9']
['nan']
['nan']
['A23']
['nan']
['B50']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B35']
['nan']
['nan']
['nan']
['D33']
['nan']
['A26']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['D48']
['nan']
['nan']
['E58']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C126']
['nan']
['B71']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B51', 'B53', 'B55']
['nan']
['D49']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B5']
['B20']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C68']
['F', 'G63']
['C62', 'C64']
['E24']
['nan']
['nan']
['nan']
['nan']
['nan']
['E24']
['nan']
['nan']
['C90']
['C124']
['C126']
['nan']
['nan']
['F', 'G73']
['C45']
['E101']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['E8']
['nan']
['nan']
['nan']
['nan']
['nan']
['B5']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B101']
['nan']
['nan']
['D45']
['C46']
['B57', 'B59', 'B63', 'B66']
['nan']
['nan']
['B22']
['nan']
['nan']
['D30']
['nan']
['nan']
['E121']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B77']
['nan']
['nan']
['nan']
['B96', 'B98']
['nan']
['D11']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['E77']
['nan']
['nan']
['nan']
['F38']
['nan']
['nan']
['B3']
['nan']
['B20']
['D6']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B82', 'B84']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['D17']
['nan']
['nan']
['nan']
['nan']
['nan']
['B96', 'B98']
['nan']
['nan']
['nan']
['A36']
['nan']
['nan']
['E8']
['nan']
['nan']
['nan']
['nan']
['nan']
['B102']
['nan']
['nan']
['nan']
['nan']
['B69']
['nan']
['nan']
['E121']
['nan']
['nan']
['nan']
['nan']
['nan']
['B28']
['nan']
['nan']
['nan']
['nan']
['nan']
['E49']
['nan']
['nan']
['nan']
['C47']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C92']
['nan']
['nan']
['nan']
['D28']
['nan']
['nan']
['nan']
['E17']
['nan']
['nan']
['nan']
['nan']
['D17']
['nan']
['nan']
['nan']
['nan']
['A24']
['nan']
['nan']
['nan']
['D35']
['B51', 'B53', 'B55']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['C50']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['nan']
['B42']
['nan']
['C148']
['nan']

In [33]:
for cabin in X['Cabin']:
    print(cabin)

nan
C85
nan
C123
nan
nan
E46
nan
nan
nan
G6
C103
nan
nan
nan
nan
nan
nan
nan
nan
nan
D56
nan
A6
nan
nan
nan
C23 C25 C27
nan
nan
nan
B78
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
D33
nan
B30
C52
nan
nan
nan
nan
nan
B28
C83
nan
nan
nan
F33
nan
nan
nan
nan
nan
nan
nan
nan
F G73
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C23 C25 C27
nan
nan
nan
E31
nan
nan
nan
A5
D10 D12
nan
nan
nan
nan
D26
nan
nan
nan
nan
nan
nan
nan
C110
nan
nan
nan
nan
nan
nan
nan
B58 B60
nan
nan
nan
nan
E101
D26
nan
nan
nan
F E69
nan
nan
nan
nan
nan
nan
nan
D47
C123
nan
B86
nan
nan
nan
nan
nan
nan
nan
nan
F2
nan
nan
C2
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
E33
nan
nan
nan
B19
nan
nan
nan
A7
nan
nan
C49
nan
nan
nan
nan
nan
F4
nan
A32
nan
nan
nan
nan
nan
nan
nan
F2
B4
B80
nan
nan
nan
nan
nan
nan
nan
nan
nan
G6
nan
nan
nan
A31
nan
nan
nan
nan
nan
D36
nan
nan
D15
nan
nan
nan
nan
nan
C93
nan
nan
nan
nan
nan
C83
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C78
nan
nan
D35
nan
nan
G6
C87
nan
nan
nan
nan
B77
nan
nan
nan
nan
E67
B94
nan
nan
nan
nan
C125
C99
nan
nan
nan
C118
nan
D7
nan
nan
nan
nan
nan
nan
nan
nan
A19
nan
nan
nan
nan
nan
nan
B49
D
nan
nan
nan
nan
C22 C26
C106
B58 B60
nan
nan
nan
E101
nan
C22 C26
nan
C65
nan
E36
C54
B57 B59 B63 B66
nan
nan
nan
nan
nan
nan
C7
E34
nan
nan
nan
nan
nan
C32
nan
D
nan
B18
nan
C124
C91
nan
nan
nan
C2
E40
nan
T
F2
C23 C25 C27
nan
nan
nan
F33
nan
nan
nan
nan
nan
C128
nan
nan
nan
nan
E33
nan
nan
nan
nan
nan
nan
nan
nan
nan
D37
nan
nan
B35
E50
nan
nan
nan
nan
nan
nan
C82
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
B96 B98
nan
nan
D36
G6
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C78
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
E10
C52
nan
nan
nan
E44
B96 B98
nan
nan
C23 C25 C27
nan
nan
nan
nan
nan
nan
A34
nan
nan
nan
C104
nan
nan
C111
C92
nan
nan
E38
D21
nan
nan
E12
nan
E63
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
D
nan
A14
nan
nan
nan
nan
nan
nan
nan
nan
B49
nan
C93
B37
nan
nan
nan
nan
C30
nan
nan
nan
D20
nan
C22 C26
nan
nan
nan
nan
nan
B79
C65
nan
nan
nan
nan
nan
nan
E25
nan
nan
D46
F33
nan
nan
nan
B73
nan
nan
B18
nan
nan
nan
C95
nan
nan
nan
nan
nan
nan
nan
nan
B38
nan
nan
B39
B22
nan
nan
nan
C86
nan
nan
nan
nan
nan
C70
nan
nan
nan
nan
nan
A16
nan
E67
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
C101
E25
nan
nan
nan
nan
E44
nan
nan
nan
C68
nan
A10
nan
E68
nan
B41
nan
nan
nan
D20
nan
nan
nan
nan
nan
nan
nan
A20
nan
nan
nan
nan
nan
nan
nan
nan
nan
C125
nan
nan
nan
nan
nan
nan
nan
nan
F4
nan
nan
D19
nan
nan
nan
D50
nan
D9
nan
nan
A23
nan
B50
nan
nan
nan
nan
nan
nan
nan
nan
B35
nan
nan
nan
D33
nan
A26
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
nan
D48
nan
nan
E58
nan
nan
nan
nan
nan
nan
C126
nan
B71
nan
nan
nan
nan
nan
nan
nan
B51 B53 B55
nan
D49
nan
nan
nan
nan
nan
nan
nan
B5
B20
nan
nan
nan
nan
nan
nan
nan
C68
F G63
C62 C64
E24
nan
nan
nan
nan
nan
E24
nan
nan
C90
C124
C126
nan
nan
F G73
C45
E101
nan
nan
nan
nan
nan
nan
E8
nan
nan
nan
nan
nan
B5
nan
nan
nan
nan
nan
nan
B101
nan
nan
D45
C46
B57 B59 B63 B66
nan
nan
B22
nan
nan
D30
nan
nan
E121
nan
nan
nan
nan
nan
nan
nan
B77
nan
nan
nan
B96 B98
nan
D11
nan
nan
nan
nan
nan
nan
E77
nan
nan
nan
F38
nan
nan
B3
nan
B20
D6
nan
nan
nan
nan
nan
nan
B82 B84
nan
nan
nan
nan
nan
nan
D17
nan
nan
nan
nan
nan
B96 B98
nan
nan
nan
A36
nan
nan
E8
nan
nan
nan
nan
nan
B102
nan
nan
nan
nan
B69
nan
nan
E121
nan
nan
nan
nan
nan
B28
nan
nan
nan
nan
nan
E49
nan
nan
nan
C47
nan
nan
nan
nan
nan
nan
nan
nan
nan
C92
nan
nan
nan
D28
nan
nan
nan
E17
nan
nan
nan
nan
D17
nan
nan
nan
nan
A24
nan
nan
nan
D35
B51 B53 B55
nan
nan
nan
nan
nan
nan
C50
nan
nan
nan
nan
nan
nan
nan
B42
nan
C148
nan

In [50]:
X[~X['Cabin'].isnull()]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
10,11,1,3,"Sandstrom, Miss. Marguerite Rut",female,4.0,1,1,PP 9549,16.7000,G6,S
11,12,1,1,"Bonnell, Miss. Elizabeth",female,58.0,0,0,113783,26.5500,C103,S
...,...,...,...,...,...,...,...,...,...,...,...,...
871,872,1,1,"Beckwith, Mrs. Richard Leonard (Sallie Monypeny)",female,47.0,1,1,11751,52.5542,D35,S
872,873,0,1,"Carlsson, Mr. Frans Olof",male,33.0,0,0,695,5.0000,B51 B53 B55,S
879,880,1,1,"Potter, Mrs. Thomas Jr (Lily Alexenia Wilson)",female,56.0,0,1,11767,83.1583,C50,C
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.0000,B42,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.0000,C148,C